In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data=pd.read_csv("census-income.csv",na_values='?')
data.head()

#,na_values='?' -> converts ? into NAN values

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country annual_income  
0          2174             0              40  United-States         <=50K  
1             0             0              13  United-States         <=50K  
2             0             0              40  United-States         <=50K  
3             0             0              40  United-States         <=50K  
4             0             0              40           Cuba         <=50K

In [ ]:
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'annual_income'],
      dtype='object')

In [ ]:
data.columns = data.columns.str.replace('-','_')

In [ ]:
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'annual_income'],
      dtype='object')

In [ ]:
for i in data.columns:
  print( data[i].unique())

[39 50 38 53 28 37 49 52 31 42 30 23 32 40 34 25 43 54 35 59 56 19 20 45
 22 48 21 24 57 44 41 29 18 47 46 36 79 27 67 33 76 17 55 61 70 64 71 68
 66 51 58 26 60 90 75 65 77 62 63 80 72 74 69 73 81 78 88 82 83 84 85 86
 87]
['State-gov' 'Self-emp-not-inc' 'Private' 'Federal-gov' 'Local-gov' nan
 'Self-emp-inc' 'Without-pay' 'Never-worked']
[ 77516  83311 215646 ...  34066  84661 257302]
['Bachelors' 'HS-grad' '11th' 'Masters' '9th' 'Some-college' 'Assoc-acdm'
 'Assoc-voc' '7th-8th' 'Doctorate' 'Prof-school' '5th-6th' '10th'
 '1st-4th' 'Preschool' '12th']
[13  9  7 14  5 10 12 11  4 16 15  3  6  2  1  8]
['Never-married' 'Married-civ-spouse' 'Divorced' 'Married-spouse-absent'
 'Separated' 'Married-AF-spouse' 'Widowed']
['Adm-clerical' 'Exec-managerial' 'Handlers-cleaners' 'Prof-specialty'
 'Other-service' 'Sales' 'Craft-repair' 'Transport-moving'
 'Farming-fishing' 'Machine-op-inspct' 'Tech-support' nan
 'Protective-serv' 'Armed-Forces' 'Priv-house-serv']
['Not-in-family' 'Husband' 'Wif

In [ ]:
data["workclass"].value_counts()

Private             22696
Self-emp-not-inc     2541
Local-gov            2093
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: workclass, dtype: int64

#Q Replace all the missing values with NA

In [ ]:
data.isnull().sum()


age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
annual_income        0
dtype: int64

In [ ]:
#Removing null values
data = data.dropna()

In [ ]:
data.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
annual_income     0
dtype: int64

# Data Manipulation questions:

###Q1 Extracting the “education” column and store it in “census_ed”

####Q2 .Extracting all the columns from “age” to “relationship” and store it in “census_seq”.

###Q3 Extract the column number “0”, “5”, “6” and store it in “census_col”.

###Q4.  Extracting all the male employees who work in state-gov and store it in “male_gov”.

###Q5. Extracting all Female employees who work in Private

###Q6. Extract all the 39 year olds who either have a bachelor's degree or who are native of the United States and store the result in “census_us”.

###Q7. Getting the count of different levels of the “workclass” column.

###Q8 Here we are calculating the mean of capital gain on the bases of work class.

###Q9 Create a separate dataframe with the details of males and females from the census data that has income more than 50,000

###Q10 Checking % of people from US who earn <=50,000 anually and work under private.

###Q11 Calculating the percentage of married people in the census data.

###Q12 Calculatig the percentage of high school graduates earning more than 50,000 annually














In [ ]:
#Data Manipulation
#Q Extractracting the “education” column and store it in “census_ed” .
census_ed=data[['education']]
census_ed.head()

education
0  Bachelors
1  Bachelors
2    HS-grad
3       11th
4  Bachelors

In [ ]:
#) Q .Extracting all the columns from “age” to “relationship” and store it in “census_seq”.
census_seq=data.iloc[:,0:8]
census_seq.head()

age         workclass  fnlwgt  education  education_num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital_status         occupation   relationship  
0       Never-married       Adm-clerical  Not-in-family  
1  Married-civ-spouse    Exec-managerial        Husband  
2            Divorced  Handlers-cleaners  Not-in-family  
3  Married-civ-spouse  Handlers-cleaners        Husband  
4  Married-civ-spouse     Prof-specialty           Wife

In [ ]:
#Q Extract the column number “0”, “5”, “6” and store it in “census_col”.
census_col=data.iloc[:,[0,5,6]]
census_col.head()

age      marital_status         occupation
0   39       Never-married       Adm-clerical
1   50  Married-civ-spouse    Exec-managerial
2   38            Divorced  Handlers-cleaners
3   53  Married-civ-spouse  Handlers-cleaners
4   28  Married-civ-spouse     Prof-specialty

In [ ]:
#)Q.  Extracting all the male employees who work in state-gov and store it in “male_gov”.
male_gov=data[(data['workclass']=='State-gov') & (data['sex']=='Male')]
male_gov.head()

age  workclass  fnlwgt     education  education_num      marital_status  \
0     39  State-gov   77516     Bachelors             13       Never-married   
11    30  State-gov  141297     Bachelors             13  Married-civ-spouse   
34    22  State-gov  311512  Some-college             10  Married-civ-spouse   
48    41  State-gov  101603     Assoc-voc             11  Married-civ-spouse   
123   29  State-gov  267989     Bachelors             13  Married-civ-spouse   

         occupation   relationship                race   sex  capital_gain  \
0      Adm-clerical  Not-in-family               White  Male          2174   
11   Prof-specialty        Husband  Asian-Pac-Islander  Male             0   
34    Other-service        Husband               Black  Male             0   
48     Craft-repair        Husband               White  Male             0   
123  Prof-specialty        Husband               White  Male             0   

     capital_loss  hours_per_week native_country annual_income  
0               0              40  United-States         <=50K  
11              0              40          India          >50K  
34              0              15  United-States         <=50K  
48              0              40  United-States         <=50K  
123             0              50  United-States          >50K

In [ ]:
#Extracting all Female employees who work in Private
female_gov=data[(data['workclass']=='Private') & (data['sex']=='Female')]
female_gov.head()

age workclass  fnlwgt  education  education_num         marital_status  \
4    28   Private  338409  Bachelors             13     Married-civ-spouse   
5    37   Private  284582    Masters             14     Married-civ-spouse   
6    49   Private  160187        9th              5  Married-spouse-absent   
8    31   Private   45781    Masters             14          Never-married   
12   23   Private  122272  Bachelors             13          Never-married   

         occupation   relationship   race     sex  capital_gain  capital_loss  \
4    Prof-specialty           Wife  Black  Female             0             0   
5   Exec-managerial           Wife  White  Female             0             0   
6     Other-service  Not-in-family  Black  Female             0             0   
8    Prof-specialty  Not-in-family  White  Female         14084             0   
12     Adm-clerical      Own-child  White  Female             0             0   

    hours_per_week native_country annual_income  
4               40           Cuba         <=50K  
5               40  United-States         <=50K  
6               16        Jamaica         <=50K  
8               50  United-States          >50K  
12              30  United-States         <=50K

In [ ]:
#Extract all the 39 year olds who either have a bachelor's degree or who are native of the United States and store the result in “census_us”.
#We are writing a condition where age should be 39 and storing it in census. This condition is then taken and applied on the
#next ont to get the result.
census=data[(data['age']==39)]
#census
census_us=census[(census['education']=='Bachelors') | (census['native_country']==' United-States')]
census_us.head()

age     workclass  fnlwgt  education  education_num      marital_status  \
0      39     State-gov   77516  Bachelors             13       Never-married   
848    39       Private  138192  Bachelors             13  Married-civ-spouse   
915    39       Private  202027  Bachelors             13  Married-civ-spouse   
999    39  Self-emp-inc  329980  Bachelors             13  Married-civ-spouse   
1336   39       Private  174938  Bachelors             13       Never-married   

           occupation   relationship   race   sex  capital_gain  capital_loss  \
0        Adm-clerical  Not-in-family  White  Male          2174             0   
848      Craft-repair        Husband  White  Male             0             0   
915   Exec-managerial        Husband  White  Male         15024             0   
999   Exec-managerial        Husband  White  Male         15024             0   
1336   Prof-specialty  Not-in-family  White  Male             0             0   

      hours_per_week native_country annual_income  
0                 40  United-States         <=50K  
848               40  United-States         <=50K  
915               45  United-States          >50K  
999               50  United-States          >50K  
1336              40  United-States         <=50K

In [ ]:
# Q sample() helps us to get random rows
census_200=data.sample(200)
census_200

age         workclass  fnlwgt     education  education_num  \
17677   37           Private  126675  Some-college             10   
11183   40           Private  187376  Some-college             10   
26567   61           Private  210488       HS-grad              9   
3452    25         State-gov  152035    Assoc-acdm             12   
18700   20           Private  229414       HS-grad              9   
...    ...               ...     ...           ...            ...   
27837   59       Federal-gov  100931       HS-grad              9   
3953    44           Private  286750  Some-college             10   
19213   23           Private  165474  Some-college             10   
10915   56           Private  172364       HS-grad              9   
13287   34  Self-emp-not-inc  108247   Prof-school             15   

           marital_status         occupation   relationship   race     sex  \
17677  Married-civ-spouse    Exec-managerial        Husband  White    Male   
11183  Married-civ-spouse              Sales        Husband  White    Male   
26567  Married-civ-spouse    Exec-managerial        Husband  White    Male   
3452        Never-married       Adm-clerical      Own-child  White  Female   
18700       Never-married  Machine-op-inspct      Own-child  White  Female   
...                   ...                ...            ...    ...     ...   
27837  Married-civ-spouse       Adm-clerical        Husband  White    Male   
3953   Married-civ-spouse   Transport-moving        Husband  Black    Male   
19213       Never-married       Craft-repair  Not-in-family  White    Male   
10915  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
13287  Married-civ-spouse     Prof-specialty        Husband  White    Male   

       capital_gain  capital_loss  hours_per_week native_country annual_income  
17677             0             0              57  United-States         <=50K  
11183             0             0              60  United-States          >50K  
26567             0             0              50  United-States          >50K  
3452              0             0              40  United-States         <=50K  
18700             0             0              30  United-States         <=50K  
...             ...           ...             ...            ...           ...  
27837             0             0              40  United-States          >50K  
3953              0             0              40  United-States         <=50K  
19213             0             0              40  United-States         <=50K  
10915             0             0              40  United-States         <=50K  
13287             0             0              55  United-States          >50K  

[200 rows x 15 columns]

In [ ]:
#Q . Getting the count of different levels of the “workclass” column.
#value_counts() helps us to get the total count of all elements present in a particular column.
data[['workclass']].value_counts()

workclass       
Private             22286
Self-emp-not-inc     2499
Local-gov            2067
State-gov            1279
Self-emp-inc         1074
Federal-gov           943
Without-pay            14
dtype: int64

In [ ]:
#Q Here we are calculating the mean of capital gain on the bases of work class
data.groupby(['workclass'])['capital_gain'].mean()

workclass
Federal-gov          832.321315
Local-gov            829.230285
Private              879.858207
Self-emp-inc        4810.746741
Self-emp-not-inc    1913.134454
State-gov            684.306489
Without-pay          487.857143
Name: capital_gain, dtype: float64

In [ ]:
#Create a separate dataframe with the details of males and females from the census data that has income more than 50,000
data['sex'].value_counts()

Male      20380
Female     9782
Name: sex, dtype: int64

In [ ]:
data.head()

age         workclass  fnlwgt  education  education_num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital_status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital_gain  capital_loss  hours_per_week native_country annual_income  
0          2174             0              40  United-States         <=50K  
1             0             0              13  United-States         <=50K  
2             0             0              40  United-States         <=50K  
3             0             0              40  United-States         <=50K  
4             0             0              40           Cuba         <=50K

In [ ]:
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'annual_income'],
      dtype='object')

In [ ]:
#Extracting males and females seperately whose income is more than 50k
male_50k=data[(data['sex']=='Male') & (data['annual_income']=='>50K')]
female_50K=data[(data['sex']=='Female') & (data['annual_income']=='>50K')]

In [ ]:
male_50k.head()

age         workclass  fnlwgt     education  education_num  \
7    52  Self-emp-not-inc  209642       HS-grad              9   
9    42           Private  159449     Bachelors             13   
10   37           Private  280464  Some-college             10   
11   30         State-gov  141297     Bachelors             13   
20   40           Private  193524     Doctorate             16   

        marital_status       occupation relationship                race  \
7   Married-civ-spouse  Exec-managerial      Husband               White   
9   Married-civ-spouse  Exec-managerial      Husband               White   
10  Married-civ-spouse  Exec-managerial      Husband               Black   
11  Married-civ-spouse   Prof-specialty      Husband  Asian-Pac-Islander   
20  Married-civ-spouse   Prof-specialty      Husband               White   

     sex  capital_gain  capital_loss  hours_per_week native_country  \
7   Male             0             0              45  United-States   
9   Male          5178             0              40  United-States   
10  Male             0             0              80  United-States   
11  Male             0             0              40          India   
20  Male             0             0              60  United-States   

   annual_income  
7           >50K  
9           >50K  
10          >50K  
11          >50K  
20          >50K

In [ ]:
female_50K.head()

age         workclass  fnlwgt    education  education_num  \
8    31           Private   45781      Masters             14   
19   43  Self-emp-not-inc  292175      Masters             14   
52   47           Private   51835  Prof-school             15   
67   53           Private  169846      HS-grad              9   
84   44           Private  343591      HS-grad              9   

        marital_status       occupation   relationship   race     sex  \
8        Never-married   Prof-specialty  Not-in-family  White  Female   
19            Divorced  Exec-managerial      Unmarried  White  Female   
52  Married-civ-spouse   Prof-specialty           Wife  White  Female   
67  Married-civ-spouse     Adm-clerical           Wife  White  Female   
84            Divorced     Craft-repair  Not-in-family  White  Female   

    capital_gain  capital_loss  hours_per_week native_country annual_income  
8          14084             0              50  United-States          >50K  
19             0             0              45  United-States          >50K  
52             0          1902              60       Honduras          >50K  
67             0             0              40  United-States          >50K  
84         14344             0              40  United-States          >50K

In [ ]:
data["annual_income"].unique()

array(['<=50K', '>50K'], dtype=object)

In [ ]:
#Checking % of people from US who earn <=50,000 anually and work under private.
p_le50k = data[(data['native_country']=='United-States') & (data['workclass']=='Private') &(data['annual_income']=='<=50K')]
total = len(data)
percentage=(len(p_le50k)/total)*100
percentage

51.70081559578277

In [ ]:
df1 = data[(data['native_country']=='United-States') & (data['workclass']=='Private') & (data['annual_income']=='<=50K')]
print(df1.shape)
df1_percentage = (df1.shape[0]/data.shape[0])*100
print('Percentage : ', df1_percentage)


(15594, 15)
Percentage :  51.70081559578277


In [ ]:
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'annual_income'],
      dtype='object')

In [ ]:
#How to know how many people above 50years have a salary of more than Rs 60,000
data['annual_income']  == ">=50"

0        False
1        False
2        False
3        False
4        False
         ...  
32556    False
32557    False
32558    False
32559    False
32560    False
Name: annual_income, Length: 30162, dtype: bool

In [ ]:
# Calculating the percentage of married people in the census data.
data['marital_status'].value_counts()

Married-civ-spouse       14065
Never-married             9726
Divorced                  4214
Separated                  939
Widowed                    827
Married-spouse-absent      370
Married-AF-spouse           21
Name: marital_status, dtype: int64

In [ ]:
total=len(data['marital_status'])
married=14065+370+21
precen_mar=(married/total)*100
precen_mar

47.92785624295471

In [ ]:
#Calculatig the percentage of high school graduates earning more than 50,000 annually
data['education'].value_counts()

HS-grad         9840
Some-college    6678
Bachelors       5044
Masters         1627
Assoc-voc       1307
11th            1048
Assoc-acdm      1008
10th             820
7th-8th          557
Prof-school      542
9th              455
12th             377
Doctorate        375
5th-6th          288
1st-4th          151
Preschool         45
Name: education, dtype: int64

In [ ]:
hs_m50k=len(data[(data['education']=='HS-grad') &(data['annual_income']=='>50K')])

percentage_hs_m50k=(hs_m50k/total)*100

percentage_hs_m50k

5.361050328227571

# **Linear Regression** **Model**

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [ ]:
lr=LinearRegression()   #making an object of linear regression class

In [ ]:
#As per the question independent variable is “education.num”.
x=data[['education_num']]
#dependent variable is “hours.per.week”
y=data['hours_per_week']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=1)
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [ ]:
y_pred   #These are the predicted values

array([40.1516711 , 38.07360531, 42.92242549, ..., 40.1516711 ,
       38.7662939 , 40.1516711 ])

In [ ]:
y_test #these are actual values

12488    65
5130     50
8616     15
15453    40
13555    50
         ..
23848    32
14755    20
11213    20
15473    40
37       25
Name: hours_per_week, Length: 9049, dtype: int64

In [ ]:
error=y_test-y_pred
error

12488    24.848329
5130     11.926395
8616    -27.922425
15453    -0.151671
13555     7.770263
           ...    
23848    -8.151671
14755   -20.844360
11213   -20.151671
15473     1.233706
37      -15.151671
Name: hours_per_week, Length: 9049, dtype: float64

In [ ]:
print('mean_squared_error :',mean_squared_error(y_test,y_pred))

print('root-mean-square error :',np.sqrt(mean_squared_error(y_test,y_pred)))

mean_squared_error : 134.69130460518096
root-mean-square error : 11.605658301241725


# **Logistic Regression Model**

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
lo=LogisticRegression()

In [ ]:
#AS per question occupation is indpendent

x=data['occupation']
x=pd.DataFrame(x)

In [ ]:
x[['occupation']].value_counts()

occupation       
Prof-specialty       4038
Craft-repair         4030
Exec-managerial      3992
Adm-clerical         3721
Sales                3584
Other-service        3212
Machine-op-inspct    1966
Transport-moving     1572
Handlers-cleaners    1350
Farming-fishing       989
Tech-support          912
Protective-serv       644
Priv-house-serv       143
Armed-Forces            9
dtype: int64

In [ ]:
#income is dependent variable
data['annual_income'].value_counts()

In [ ]:
y=data['annual_income'].replace('<=50K',0).replace('>50K',1)
y.value_counts()

0    22654
1     7508
Name: annual_income, dtype: int64

In [ ]:
# giving particular labels to the elements in my columns
L=LabelEncoder()

In [ ]:
x=L.fit_transform(x)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
x=pd.DataFrame(x)

In [ ]:
x.head()

0
0  0
1  3
2  5
3  5
4  9

In [ ]:
x.to_string()  #to check the labels of whole column.

'        0\n0       0\n1       3\n2       5\n3       5\n4       9\n5       3\n6       7\n7       3\n8       9\n9       3\n10      3\n11      9\n12      0\n13     11\n14     13\n15      4\n16      6\n17     11\n18      3\n19      9\n20      7\n21      4\n22     13\n23     12\n24     12\n25      2\n26      3\n27      2\n28     10\n29     11\n30      3\n31      0\n32      7\n33      6\n34      6\n35      0\n36      9\n37      6\n38      9\n39     12\n40      0\n41      5\n42      9\n43      6\n44      3\n45      2\n46      9\n47      3\n48      9\n49      3\n50      3\n51     12\n52      6\n53      7\n54      0\n55      6\n56     11\n57     13\n58      9\n59     12\n60      2\n61      0\n62      0\n63      3\n64      9\n65     11\n66     11\n67      6\n68      9\n69      7\n70      0\n71      7\n72      4\n73     11\n74      7\n75      7\n76     11\n77      2\n78     11\n79     10\n80      9\n81     11\n82      9\n83      9\n84      2\n85      6\n86     10\n87      5\n88      9\n89     11

In [ ]:
x.value_counts()

9     4038
2     4030
3     3992
0     3721
11    3584
7     3212
6     1966
13    1572
5     1350
4      989
12     912
10     644
8      143
1        9
dtype: int64

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.35,random_state=1)
lo=LogisticRegression()
lo.fit(x_train,y_train)
y_pred=lo.predict(x_test)

print('confusion_matrix :')
print(confusion_matrix(y_pred,y_test))
print('accuracy_score :',accuracy_score(y_test,y_pred))

confusion_matrix :
[[7932 2625]
 [   0    0]]
accuracy_score : 0.7513498152884343


In [ ]:
data.head(1)

age  workclass  fnlwgt  education  education_num marital_status  \
0   39  State-gov   77516  Bachelors             13  Never-married   

     occupation   relationship   race   sex  capital_gain  capital_loss  \
0  Adm-clerical  Not-in-family  White  Male          2174             0   

   hours_per_week native_country annual_income  
0              40  United-States         <=50K

In [ ]:
d=data[['age','workclass','education']]    #We are taking this because income is most related to these columns
d.head()

age         workclass  education
0   39         State-gov  Bachelors
1   50  Self-emp-not-inc  Bachelors
2   38           Private    HS-grad
3   53           Private       11th
4   28           Private  Bachelors

In [ ]:
d['workclass'].value_counts()

Private             22286
Self-emp-not-inc     2499
Local-gov            2067
State-gov            1279
Self-emp-inc         1074
Federal-gov           943
Without-pay            14
Name: workclass, dtype: int64

In [ ]:
x=d.apply(L.fit_transform)
x.head()

age  workclass  education
0   22          5          9
1   33          4          9
2   21          2         11
3   36          2          1
4   11          2          9

In [ ]:
y=data['annual_income'].replace('<=50K',0).replace('>50K',1)

In [ ]:
y.value_counts()

0    22654
1     7508
Name: annual_income, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=1)
lo=LogisticRegression()
lo.fit(x_train,y_train)
y_pred=lo.predict(x_test)

print('confusion_matrix :')
print(confusion_matrix(y_pred,y_test))
print('accuracy_score :',accuracy_score(y_test,y_pred))

confusion_matrix :
[[4349 1499]
 [ 134   51]]
accuracy_score : 0.7293220619923753


*TP* FP
FN TN

PRECISION  = TP/TP+FP

RECALL     = TP/ TP+ FN

F-1 SCORE  = WEIGHTED HARMOINC MEAN

SUPPORT = NO.OF ITEMS IN DATASET.

TP - TRUE POSITIVE

TN - TRUE NEGATIVE

FN - FALSE NEGATIVE   TYPE 1 ERROR

FP - FALSE POSITIVE   TYPE II ERROR

# **Decision Tree Model**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
data.head()

age  workclass  fnlwgt  education  education_num  marital_status  \
0   22          5    2491          0             12               1   
1   33          4    2727          0             12               0   
2   21          2   13188          2              8               2   
3   36          2   14354          5              6               0   
4   11          2   18120          0             12               0   

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           0             1     4    1            24             0   
1           3             0     4    1             0             0   
2           5             1     4    1             0             0   
3           5             0     2    1             0             0   
4           9             5     2    0             0             0   

   hours_per_week  native_country  annual_income  
0              39              38              0  
1              12              38              0  
2              39              38              0  
3              39              38              0  
4              39               4              0

In [ ]:
data.education= data.education.replace(['Preschool', '1st-4th', '5th-6th', '7th-8th', '9th','10th', '11th', '12th'], 'School')
data.education = data.education.replace(['Assoc-voc', 'Assoc-acdm', 'Prof-school', 'Some-college'], 'Higher')
data['marital_status']= data['marital_status'].replace(['Married-civ-spouse', 'Married-AF-spouse'], 'married')
data['marital_status']= data['marital_status'].replace(['Never-married'], 'not-married')
data['marital_status']= data['marital_status'].replace(['Divorced', 'Separated','Widowed','Married-spouse-absent'], 'other')
data.annual_income = data.annual_income.replace('<=50K', 0)
data.annual_income = data.annual_income.replace('>50K', 1)
data.head()

age  workclass  fnlwgt  education  education_num  marital_status  \
0   22          5    2491          0             12               1   
1   33          4    2727          0             12               0   
2   21          2   13188          2              8               2   
3   36          2   14354          5              6               0   
4   11          2   18120          0             12               0   

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           0             1     4    1            24             0   
1           3             0     4    1             0             0   
2           5             1     4    1             0             0   
3           5             0     2    1             0             0   
4           9             5     2    0             0             0   

   hours_per_week  native_country  annual_income  
0              39              38              0  
1              12              38              0  
2              39              38              0  
3              39              38              0  
4              39               4              0

In [ ]:
data=data.apply(L.fit_transform)
data.head()

age  workclass  fnlwgt  education  education_num  marital_status  \
0   22          5    2491          0             12               1   
1   33          4    2727          0             12               0   
2   21          2   13188          2              8               2   
3   36          2   14354          5              6               0   
4   11          2   18120          0             12               0   

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           0             1     4    1            24             0   
1           3             0     4    1             0             0   
2           5             1     4    1             0             0   
3           5             0     2    1             0             0   
4           9             5     2    0             0             0   

   hours_per_week  native_country  annual_income  
0              39              38              0  
1              12              38              0  
2              39              38              0  
3              39              38              0  
4              39               4              0

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=1)
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

print('confusion_matrix :')
print(confusion_matrix(y_pred,y_test))
print('accuracy_score :',accuracy_score(y_test,y_pred))

confusion_matrix :
[[6203 1481]
 [ 566  799]]
accuracy_score : 0.7737871588020776


# **Random Forest Model**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=1)
rf=RandomForestClassifier(n_estimators=300)
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

print('confusion_matrix :')
print(confusion_matrix(y_pred,y_test))
print('accuracy_score :',accuracy_score(y_test,y_pred))

confusion_matrix :
[[4049  964]
 [ 434  586]]
accuracy_score : 0.7682744903033317


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.90      0.85      4483
           1       0.57      0.38      0.46      1550

    accuracy                           0.77      6033
   macro avg       0.69      0.64      0.65      6033
weighted avg       0.75      0.77      0.75      6033

